Repository Yoshi-s-Yodelers/BookIt, pull requests merged in 2021-10, with the labels that each got.

#50 Extension init
  .env.example
  .gitignore
  babel.config.json
  client/popup/app.js
  client/popup/index.js
  package-lock.json
  package.json
  public/manifest.json
  public/popup.html
  webpack.config.js
Labels: extension

#55 Popup: Fetching URL
  client/popup/app.js
  client/popup/index.js
  client/store/index.js
  client/store/tab.js
  script/seed.js
  server/db/index.js
Labels: extension

#102 Author/main
  README.md
  package-lock.json
  package.json
  script/seed.js
  server/db/index.js
  server/db/models/Author.js
Labels: Tier 1

#103 Author Express Routes
  .env.example
  server/api/authors.js
  server/api/index.js
  server/index.js
Labels: Tier 1, api

#114 Author/state
  client/store/index.js
  client/store/singleAuthor.js
Labels: Tier 1

#129 feat: Users now have a one-to-one relationship with authors
  script/seed.js
  server/db/index.js
Labels: user, db, Author

#131 Created tag filter with displaying all tags of specific user
  client/components/Navigation/FormFilters.js
  client/components/Navigation/MainMenu.js
  client/components/Navigation/TagFilter.js
  client/components/SingleArticle.js
  client/components/UserArticles.js
  client/store/tag.js
  client/store/userArticles.js
  server/api/articles.js
  server/api/tags.js
  server/api/userArticles.js
  server/db/models/Tag.js
  server/db/models/Tagging.js
  server/db/models/UserArticle.js
Labels: Articles, Tag, userArticles

#142 Updated filter tab with private/read marks
  client/components/Navigation/TagFilter.js
  client/components/SingleArticle.js
  client/components/UserArticles.js
  client/store/userArticles.js
  server/api/tags.js
  server/api/userArticles.js
Labels: Articles, UI

#148 fix: fixing empty author list crash
  client/components/SingleArticle.js
Labels: bug, Articles, Author
